---
- name: Configurar Fedora
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Driver Nvidia
      ansible.builtin.import_tasks: tasks/000-nvidia.yml

    - name: Pacotes
      ansible.builtin.import_tasks: tasks/010-pacotes.yml

    - name: Flatpak
      ansible.builtin.import_tasks: tasks/020-flatpak.yml

    - name: GNOME
      ansible.builtin.import_tasks: tasks/030-gnome.yml

    - name: Extensões GNOME
      ansible.builtin.import_tasks: tasks/040-extensões-gnome.yml
