---
- name: Repositório Flatpak
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system
    state: present

- name: Instalação dos Flatpak
  community.general.flatpak:
    name:
      - com.mattjakeman.ExtensionManager
      - net.nokyan.Resources
      - app.zen_browser.zen
      - org.prismlauncher.PrismLauncher
      - com.obsproject.Studio
      - com.vscodium.codium
      - com.spotify.Client
    remote: flathub
    method: system
    state: present

- name: Atualizar Flatpaks
  ansible.builtin.command: flatpak update --system -y
